### ISSUE TITLE
don't overwrite existing panic hooks

### ISSUE THREAD

**Issue by mockersf** [Koranir/bevy-panic-handler#1]
This library currently use `set_hook`, which will replace any panic handler already set: https://github.com/Koranir/bevy-panic-handler/blob/66475c1abbbb5f4bf0771ecd9085550e9faee45b/src/lib.rs#L12

In a library, it is nicer to first use [`take_hook`](https://doc.rust-lang.org/stable/std/panic/fn.take_hook.html) and call the previous hook at the end of your new one

**Comment by Koranir** [comment]
Thanks for the advice! I've added some functions to implement this.
