### ISSUE TITLE
Disable default features

### ISSUE THREAD

**Issue by voidentente** [Koranir/bevy-panic-handler#2]
This crate single-handedly increases the amount of dependencies I have to build by 150. Part of the issue might be that you include all default bevy features: 

https://github.com/Koranir/bevy-panic-handler/blob/4303d7cd52812aac8bc0fd09503a5a294e40f6c3/Cargo.toml#L13

Consider changing this line to:

```
[dependencies.bevy]
version = "0.11.2"
default-features = false
```

**Comment by Koranir** [comment]
Fixed, thanks for the notice.
